### ISSUE TITLE
Bug: Interferes with project view

### ISSUE THREAD

**Issue by spocko** [fabiocchetti/widegithub#2]
When viewing projects, github natively uses the full screen width. This addon causes the view to be narrower, so it no longer fills the screen horizontally.

**Comment by fabiocchetti** [comment]
Hi @spocko, thanks for reporting.

It should be fixed on version 1.1.0.

Since I don't have access to any project view on GitHub, I've been unable to test it. Please file a new issue if it's still not working as expected.

**Comment by spocko** [comment]
Looks good, thanks!

For future reference, here's an example project board that's in a public repo:

https://github.com/fabiocchetti/widegithub/issues/2#event-2531940988
