### ISSUE TITLE
Seems to not work with latest github (& Firefox 70.0)

### ISSUE THREAD

**Issue by vvuk** [fabiocchetti/widegithub#4]
Github seems to be no longer wide.  Octotree also has some weird layout issues, so it's possible github changed their layout code.

This is with Firefox 70.0, in case the browser is screwing things up.  Haven't had a chance to try with Chrome yet.

**Comment by vvuk** [comment]
Actually, something weird is happening.  I'm on a 4K display with Windows scaling set to 125%.  But looking at the styles that get applied, it's like the min-width for 1800px is not triggering, only the 1400px?  The toplevel HTML element has a width of 3055.2.

![20191023-121910](https://user-images.githubusercontent.com/194965/67426814-b9edab00-f58f-11e9-9150-7c34495d49bc.png)

**Comment by fabiocchetti** [comment]
Hello @vvuk, thanks for reporting and for your suggestions.

I'll look into this asap and let you know.

**Comment by fabiocchetti** [comment]
@vvuk Fixed with version 1.2.0, just published on Mozilla Add-ons repo.

Thank you once more for reporting!
