### ISSUE TITLE
Support for GitHub Enterprise

### ISSUE THREAD

**Issue by henrik242** [fabiocchetti/widegithub#5]
@fabiocchetti  Would it be possible to add support for github enterprise?  Currently this extension doesn't support URLs other than `github.com` (ours is similar to `github.example.io`)

**Comment by MahatmaFatalError** [comment]
IMHO github.*.io is too limited. Can't this be freeley configurable?

**Comment by fabiocchetti** [comment]
@henrik242 Thank you for your contribution. Your PR was merged and released with version 2.0.0.
@MahatmaFatalError I don't know how GitHub Enterprise domains work. Isn't the URL structure always `github.*.io`? Could you provide me with more examples? Thanks a lot.

**Comment by MahatmaFatalError** [comment]
@fabiocchetti the Domain is freely configurable by the company. So IMHO '*' would be the only valid pattern.

**Comment by fabiocchetti** [comment]
I understand. Please see #12.

**Comment by fabiocchetti** [comment]
👋 I'm aware that a few years have passed, but this feature is [fully supported](https://addons.mozilla.org/en-US/firefox/addon/widegithub/) now (also [on Chrome](https://chromewebstore.google.com/detail/wide-github/hohnneiphpemlbhmiiipkfjnfhmnobpo)).
